sudo: required

language: php

services:
  - redis-server

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer update -n --prefer-dist

  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar

before_script:
  - export AMP_DEBUG=true
  - export AMP_HTTP_SERVER_SESSION_REDIS_TESTS=true

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - ./coveralls.phar -v

cache:
  directories:
    - $HOME/.php-cs-fixer
    - $HOME/.composer/cache
